# Generated by Django 4.2.6 on 2023-10-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='header_logo')),
                ('header_phone_umber', models.CharField(max_length=20)),
                ('header_email', models.CharField(max_length=30)),
                ('header_address', models.TextField()),
                ('footer_license', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Site Settings',
            },
        ),
    ]
