# Generated by Django 4.2.6 on 2023-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=100)),
                ('body1', models.TextField()),
                ('header2', models.CharField(max_length=100)),
                ('body2', models.TextField()),
                ('header3', models.CharField(max_length=100)),
                ('body3', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Home Settings',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
