# Generated by Django 4.2.6 on 2023-10-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0003_alter_homedetails_body1_alter_homedetails_body2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='thumbnail',
            new_name='favicon',
        ),
    ]
