# Generated by Django 4.2.6 on 2023-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_rename_thumbnail_sitesetting_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(blank=True, max_length=100, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('header2', models.CharField(blank=True, max_length=100, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('header3', models.CharField(blank=True, max_length=100, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'About Us Settings',
            },
        ),
        migrations.CreateModel(
            name='OurServicesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(blank=True, max_length=100, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('header2', models.CharField(blank=True, max_length=100, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('header3', models.CharField(blank=True, max_length=100, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Our Services Settings',
            },
        ),
    ]
