# Generated by Django 4.2.6 on 2023-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0005_aboutusdetails_ourservicesdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Slider Settings',
            },
        ),
    ]
